### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Ballantines1994** [Lunar-Scripts/lunar_garage#10]
If you go in the interior and picked up the car, the displays always doubled.
![FiveM® by Cfx re 17 09 2023 14_26_02](https://github.com/Lunar-Scripts/lunar_garage/assets/126023569/ac31280c-a396-42bb-aa43-be29fc606fb0)

**Comment by Lunar-Scripts** [comment]
What framework are you on?

**Comment by Ballantines1994** [comment]
ESX Legacy

**Comment by Lunar-Scripts** [comment]
I was unable to reproduce this behaviour, try to update to latest ox_target and the latest release of lunar_garage.

**Comment by Ballantines1994** [comment]
I have the latest release from you’re script and ox_target.

**Comment by UnboundGodz** [comment]
> I have the latest release from you’re script and ox_target.

do you have any other scripts to do with garages? Could be conflicting abit. Or, it could be a resource start order issue.

**Comment by Lunar-Scripts** [comment]
Please try to download the latest source code, I just pushed an commit that might fix it for you.
Let me know how it goes.

**Comment by Ballantines1994** [comment]
Yes you was solve the problem. Thanks!
