### ISSUE TITLE
[Bug] Error when exiting a vehicle from the garage

### ISSUE THREAD

**Issue by rayzenoam** [Lunar-Scripts/lunar_garage#13]
Hello to you!
When I put a vehicle in my garage and then take it out, it's immediately impounded without explanation and without any errors in my console. Then, when I try to take it out of the impound, I receive a notification as if I don't have enough money, and I get an error in my server-side console.

I am on the latest version of the QB-Core framework.

![image](https://github.com/Lunar-Scripts/lunar_garage/assets/95571372/de4acf5f-ba8e-425a-a70b-e39a5302dcb3)

**Comment by Lunar-Scripts** [comment]
Update your server artifacts.
