### ISSUE TITLE
bug when pushing E to choose vehicle then breaks the script stuck in garage

### ISSUE THREAD

**Issue by XoHydroX** [Lunar-Scripts/lunar_garage#14]
MainThrd/ ^1SCRIPT ERROR: Error executing native 0x2f5a72430e78c8d3 at address (nil).^7
MainThrd/ ^3> ref^7 (^5@ox_lib/resource/vehicleProperties/client.lua^7:272)
MainThrd/ ^3> cb^7 (^5@lunar_garage/client/interior.lua^7:11)
MainThrd/ ^3> fn^7 (^5@lunar_garage/utils/cl_main.lua^7:162)

MainThrd/ ^1SCRIPT ERROR: @lunar_garage/client/interior.lua:11: 
MainThrd/ ^5 An error occurred while calling export `getVehicleProperties` in resource `ox_lib`:

**Comment by Nighty420** [comment]
Update ox_lib?
