### ISSUE TITLE
This is the screenhot of the error when i try to put in the vehicle in my garage. I use the newest ox_lib

### ISSUE THREAD

**Issue by Jeffrey-jumbo** [Lunar-Scripts/lunar_garage#16]
https://cdn.discordapp.com/attachments/1153349518780284998/1156550453924995072/Screenshot_2023-09-27_131320.png?ex=6515610b&is=65140f8b&hm=dc0611e8c717b960412efa4ee845dee50b41ef7d95c3f3bb69297eb15de6b9d2&

This is the screenhot of the error when i try to put in the vehicle in my garage. I use the newest ox_lib

**Comment by carbonaming** [comment]
im having an issue too with puting the vehicles into the grage its saying an error occurred while calling export 'getvehicleproperties' in resource 'ox_lib' ive tried reinstalling ox lib and lunar grage but it isnt fixed
