### ISSUE TITLE
Multiple attempt to index nil value (global 'lib') and (global 'Utils') issues

### ISSUE THREAD

**Issue by muleyau** [Lunar-Scripts/lunar_garage#17]
![image](https://github.com/Lunar-Scripts/lunar_garage/assets/147155513/ae1c1de4-b145-4c98-b10b-95e44e10c307)
screenshot of console once ensuring. completely new to coding so have no idea what the issues are. 
have looked through the files and lines that the issues are on but cant figure it out.

**Comment by DevX32** [comment]
> ![image](https://user-images.githubusercontent.com/147155513/273189687-ae1c1de4-b145-4c98-b10b-95e44e10c307.png) screenshot of console once ensuring. completely new to coding so have no idea what the issues are. have looked through the files and lines that the issues are on but cant figure it out.

u should start ox_lib before garages
