### ISSUE TITLE
I followed the exact instructions and errors won't go away

### ISSUE THREAD

**Issue by Peso773** [Lunar-Scripts/lunar_garage#22]
I have been playing wak a mole 2 days now I fix an error another pops up non stop now I hit a wall I own the vehicle but says I don't this is the error I can't get rid of also a clip showing i try to save but says I don't own the car.
https://medal.tv/games/gta-v/clips/1GaEULZd-GFiVQ/d1337yPrxgoi?invite=cr-MSwyT0csMTI0MDU1MDg4LA

 script:oxmysql] Error: qb-adminmenu was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO player_vehicles (license, citizenid, vehicle, hash, mods, plate, state) VALUES (?, ?, ?, ?, ?, ?, ?)
[      script:oxmysql] ["license:e5c1119ed2ba931912022521e2186f3d002ab43f","RZX42752","18ZL14Door",588719872,"{\"modHydrolic\":-1,\"windowStatus\":{\"1\":true,\"2\":true,\"3\":true,\"4\":true,\"5\":true,\"6\":true,\"7\":true,\"0\":true},\"wheelColor\":156,\"modWindows\":-1,\"modSteeringWheel\":-1,\"modAPlate\":-1,\"engineHealth\":1000.0592475178704,\"pearlescentColor\":146,\"modKit47\":-1,\"modAerials\":-1,\"modRoof\":-1,\"modOrnaments\":-1,\"xenonColor\":255,\"doorStatus\":{\"1\":false,\"2\":false,\"3\":false,\"4\":false,\"5\":false,\"0\":false},\"modKit49\":-1,\"modSpoilers\":-1,\"modFrontWheels\":-1,\"wheels\":1,\"wheelWidth\":0.0,\"modDoorSpeaker\":-1,\"modEngine\":-1,\"modSmokeEnabled\":false,\"modRightFender\":-1,\"modFrame\":-1,\"modDashboard\":-1,\"modFender\":-1,\"interiorColor\":156,\"modSeats\":-1,\"modAirFilter\":-1,\"modGrille\":-1,\"modCustomTiresR\":false,\"modTurbo\":false,\"modExhaust\":-1,\"modSuspension\":-1,\"modBrakes\":-1,\"modEngineBlock\":-1,\"plate\":\"04DJQ239\",\"neonEnabled\":[false,false,false,false],\"modBackWheels\":-1,\"plateIndex\":0,\"dirtLevel\":0.0,\"modKit21\":-1,\"modDial\":-1,\"modSideSkirt\":-1,\"modRearBumper\":-1,\"modTrunk\":-1,\"modArmor\":-1,\"modFrontBumper\":-1,\"modVanityPlate\":-1,\"modKit17\":-1,\"fuelLevel\":77.84416700297959,\"modTank\":-1,\"headlightColor\":255,\"tireBurstCompletely\":{\"1\":false,\"2\":false,\"3\":false,\"4\":false,\"5\":false,\"0\":false},\"modXenon\":false,\"wheelSize\":0.0,\"tireHealth\":{\"1\":1000.0,\"2\":1000.0,\"3\":1000.0,\"0\":1000.0},\"extras\":{\"12\":true,\"11\":false},\"modBProofTires\":false,\"oilLevel\":4.76596940834568,\"color2\":146,\"tireBurstState\":{\"1\":false,\"2\":false,\"3\":false,\"4\":false,\"5\":false,\"0\":false},\"bodyHealth\":1000.0592475178704,\"modTransmission\":-1,\"modCustomTiresF\":false,\"windowTint\":-1,\"liveryRoof\":-1,\"color1\":146,\"dashboardColor\":156,\"modStruts\":-1,\"modTrimB\":-1,\"tyreSmokeColor\":[255,255,255],\"modLivery\":-1,\"modSpeakers\":-1,\"model\":588719872,\"modTrimA\":-1,\"modArchCover\":-1,\"tankHealth\":1000.0592475178704,\"modHorns\":-1,\"modDrift\":false,\"modPlateHolder\":-1,\"modKit19\":-1,\"modHood\":-1,\"neonColor\":[255,0,255],\"modShifterLeavers\":-1}","04DJQ239",0]
[      script:oxmysql] Unknown column 'mods' in 'field list'

**Comment by Lunar-Scripts** [comment]
This is a qb-adminmenu issue.
