### ISSUE TITLE
After server restart taking out vehicle doesnt work anymore. (MORE USERS HAVE THIS PROBLEM!)

### ISSUE THREAD

**Issue by BlundSiepel** [Lunar-Scripts/lunar_garage#26]
hey! i love the lunar garage script but i got a problem.. everything works but after a server restart you cant get your car out of the garage... and if you try to take it out of the interieur option its going to be stucked in a black loadscreen... anyone has this issue before and know how to fix it? im using esx.

**Comment by BlundSiepel** [comment]
I noticed that its only happens to the cars you bought and are saved before a server restart... so when a server restart you cant get the cars out of the garage.. not saying any error.. but if you bought a new car you can save it and take it out till the server restart again xD

**Comment by Lunar-Scripts** [comment]
Can you export your owned_vehicles table and send it over?
