### ISSUE TITLE
[Request?] Persistent vehicle

### ISSUE THREAD

**Issue by Artoria01** [Lunar-Scripts/lunar_garage#28]
Hello, on your post CFX.re it is mentioned about [persistent vehicle] I would like to know how it works on lunar because I can't find anything in the config file, and the vehicles are impounded after a reboot, could you add a feature so that the position of the players' vehicles is saved and the vehicles respawn after a reboot? 

Thank you for your work.

**Comment by Lunar-Scripts** [comment]
It wasn't meant like this. The vehicles are spawned server side which means they can't despawn. That's what I meant by persistent.
