### ISSUE TITLE
ox target almost impossible to use

### ISSUE THREAD

**Issue by JeffreyKroonenberg** [Lunar-Scripts/lunar_garage#9]
I would like to see target included in the config that is much easier to set up than it currently is

**Comment by Lunar-Scripts** [comment]
The current system allows you to toggle target per garage/impound however I can see how this might be too tedious for some users. I will add an global toggle for target.

**Comment by Lunar-Scripts** [comment]
Done, added in the latest commit.

**Comment by Lunar-Scripts** [comment]
Done, added in the latest commit.
